=== JorgeGomez123/Tarea_Git/tienda.dtd
<!DOCTYPE tienda [
    <!ELEMENT tienda (cliente+)>
    <!ELEMENT cliente (nombre, direccion+, telefono?, compras?)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT direccion (calle | apartado | ciudad)>
    <!ELEMENT calle (#PCDATA)>
    <!ELEMENT apartado (#PCDATA)>
    <!ELEMENT ciudad (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>
    <!ELEMENT compras (producto+)>
    <!ELEMENT producto (codigo, tipo, peso?)>
    <!ELEMENT codigo (#PCDATA)>
    <!ELEMENT tipo (#PCDATA)>
    <!ELEMENT peso (#PCDATA)>
]>

=== JorgeGomez123/Tarea_Git/tienda.xml
<?xml version="1.0"?>
<!DOCTYPE tienda SYSTEM "tienda.dtd">
<tienda>
    <cliente>
        <nombre>Jorge</nombre>
        <direccion>
            <calle>Calle Río Ter</calle>
            <ciudad>Leganés</ciudad>
        </direccion>
        <telefono>620149787</telefono>
        <compras>
            <producto>
                <codigo>123456</codigo>
                <tipo>Gaming</tipo>
                <peso>15 kg</peso>
            </producto>
            <producto>
                <codigo>789012</codigo>
                <tipo>Ropa</tipo>
            </producto>
        </compras>
    </cliente>
    <cliente>
        <nombre>Sandra</nombre>
        <direccion>
            <apartado>Apartado 243</apartado>
            <ciudad>Getafe</ciudad>
        </direccion>
        <compras>
            <producto>
                <codigo>875643</codigo>
                <tipo>Electrónico</tipo>
            </producto>
        </compras>
    </cliente>
</tienda>
